" Remap comma as the leader key.
let mapleader=','

" Set duration for time-out.
set timeoutlen=50


" Disable mouse support.
set mouse=


" Switch syntax highlighting on.
syntax on

" Make backspace behave in a sane manner.
set backspace=indent,eol,start

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on


" Improve usability when making a search.
set ignorecase smartcase

" Highlight matches when typing a search term.
set hlsearch incsearch


" " Show the ordered sequence of items.
" set list

" Display extra whitespaces.
if &listchars ==# 'eol:$'
  if has('multi_byte') && &encoding ==# 'utf-8'
    set listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮,nbsp:±
  else
    set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
  endif
endif


" Load theme configuration from external file.
if filereadable(expand($HOME . "/.vimrc.d/theme"))
    source $HOME/.vimrc.d/theme
endif
