#!/bin/bash

# shellcheck disable=SC1090
[ -n "${BASH_VERSION}" ] && [ -f "${HOME}/.bashrc" ] && . "${HOME}/.bashrc"

[ -d "${HOME}/.bin" ] && PATH="${HOME}/.bin:${PATH}"
[ -d "${HOME}/.local/bin" ] && PATH="${HOME}/.local/bin:${PATH}"
